<?php
declare(strict_types=1);

if (!defined('ABSPATH')) {
    exit;
}

if (!function_exists('underscores_child_render_flexible_sections')) {
    function underscores_child_render_flexible_sections(string $field_name = 'sections', ?int $post_id = null): bool
    {
        $rendered = false;

        if (!function_exists('have_rows')) {
            return false;
        }

        $post_id = $post_id ?: (int) get_the_ID();

        if ($post_id <= 0 || !have_rows($field_name, $post_id)) {
            return false;
        }

        while (have_rows($field_name, $post_id)) {
            the_row();

            $layout = (string) get_row_layout();

            if ($layout === '') {
                continue;
            }

            $template_slug = 'partials/sections/' . str_replace('_', '-', $layout);

            if (!locate_template($template_slug . '.php', false, false)) {
                continue;
            }

            get_template_part(
                $template_slug,
                null,
                [
                    'layout' => $layout,
                    'post_id' => $post_id,
                ]
            );

            $rendered = true;
        }

        return $rendered;
    }
}

if (!function_exists('underscores_child_extract_headings')) {
    /**
     * Extract <h2> headings from HTML content and assign unique IDs.
     *
     * Preserves existing ids when possible; appends -2, -3, ... for duplicates.
     * Shared by the TOC and the heading-id filter so both stay in sync.
     *
     * @param string $content
     * @return array<int,array{id:string,text:string}>
     */
    function underscores_child_extract_headings(string $content): array
    {
        if (!preg_match_all('#<h2([^>]*)>(.*?)</h2>#is', $content, $matches, PREG_SET_ORDER)) {
            return [];
        }

        $headings = [];
        $used     = [];

        foreach ($matches as $m) {
            $attrs = $m[1];
            $html  = $m[2];
            $text  = trim(wp_strip_all_tags($html));

            if ($text === '') {
                continue;
            }

            // Prefer an existing id attribute; otherwise slugify the heading text.
            if (preg_match('/\bid\s*=\s*["\']?([^"\'>\s]+)/i', $attrs, $id_match)) {
                $base_id = $id_match[1];
            } else {
                $base_id = sanitize_title($text);
                if ($base_id === '') {
                    continue;
                }
            }

            // Make duplicate ids unique deterministically.
            $id    = $base_id;
            $count = 1;
            while (isset($used[$id])) {
                $id = $base_id . '-' . ++$count;
            }

            $used[$id] = true;
            $headings[] = ['id' => $id, 'text' => $text];
        }

        return $headings;
    }
}

if (!function_exists('underscores_child_add_heading_ids')) {
    /**
     * Add unique id attributes to <h2> headings in single post content.
     * IDs match the TOC generated by partials/components/post-toc.php.
     *
     * @param string $content
     * @return string
     */
    function underscores_child_add_heading_ids($content)
    {
        if (!is_singular('post')) {
            return $content;
        }

        $headings = underscores_child_extract_headings($content);
        if (empty($headings)) {
            return $content;
        }

        $index = 0;
        return preg_replace_callback(
            '#<h2([^>]*)>(.*?)</h2>#is',
            static function ($m) use (&$index, $headings) {
                $attrs   = $m[1];
                $html    = $m[2];
                $heading = $headings[$index++] ?? null;
                if (! $heading) {
                    return $m[0];
                }

                // Already correct — keep the original markup.
                if (preg_match('/\bid\s*=\s*["\']?' . preg_quote($heading['id'], '/') . '["\']?/i', $attrs)) {
                    return $m[0];
                }

                // Otherwise overwrite any existing id to guarantee uniqueness.
                if (preg_match('/\bid\s*=/i', $attrs)) {
                    $attrs = preg_replace('/\bid\s*=\s*["\']?[^"\'>\s]+["\']?/i', '', $attrs);
                    $attrs = trim($attrs);
                }

                return '<h2' . ($attrs !== '' ? ' ' . $attrs : '') . ' id="' . esc_attr($heading['id']) . '">' . $html . '</h2>';
            },
            $content
        );
    }
}
add_filter('the_content', 'underscores_child_add_heading_ids', 20);

/**
 * Add the design's `.logo` class to the custom-logo link so header styling
 * applies without wrapping it in a second anchor. Hooked only around the
 * the_custom_logo() call in header.php.
 */
function underscores_child_logo_class(string $html): string
{
    return str_replace('class="custom-logo-link"', 'class="custom-logo-link logo"', $html);
}

if (!function_exists('get_main_class')) {
    /**
     * Build the class attribute for the page <main> wrapper.
     *
     * Pulls any classes registered via underscores_child_set_main_class()
     * (e.g. from page-specific Hook classes — AboutPageHook, AuthorPageHook,
     * ContactPageHook all do this on their body_class filter) and merges
     * them with an optional $css_class arg + the base 'main'. Output is
     * `class="..."` ready to drop into the markup.
     *
     * The `main_class` filter lets other code (incl. the page Hooks above)
     * add/tweak classes without touching the global directly.
     *
     * @param string|array $css_class Optional class(es) to add for this call.
     * @return string `class="..."` or empty when no classes survive sanitization.
     */
    function get_main_class($css_class = ''): string
    {
        $classes           = ['main'];
        $registered_classes = $GLOBALS['underscores_child_main_class'] ?? '';

        if (!empty($registered_classes)) {
            if (!is_array($registered_classes)) {
                $registered_classes = preg_split('#\s+#', (string) $registered_classes);
            }

            $classes = array_merge($classes, $registered_classes);
        }

        if (!empty($css_class)) {
            if (!is_array($css_class)) {
                $css_class = preg_split('#\s+#', (string) $css_class);
            }

            $classes = array_merge($classes, $css_class);
        }

        $classes = apply_filters('main_class', $classes, $css_class);
        $classes = array_filter(array_map('sanitize_html_class', array_unique((array) $classes)));

        if ($classes === []) {
            return '';
        }

        return sprintf('class="%s"', esc_attr(implode(' ', $classes)));
    }
}

if (!function_exists('main_class')) {
    /**
     * Echo the class attribute for the page <main> wrapper. Companion to
     * get_main_class() for the `<?php main_class(); ?>` shorthand.
     */
    function main_class($css_class = ''): void
    {
        echo get_main_class($css_class);
    }
}

if (!function_exists('underscores_child_set_main_class')) {
    /**
     * Register extra class(es) that should land on the next <main> wrapper
     * rendered via get_main_class(). Page Hooks (About/Author/Contact) call
     * this from their body_class filter so the value sticks until the main
     * is rendered.
     */
    function underscores_child_set_main_class($css_class = ''): void
    {
        $GLOBALS['underscores_child_main_class'] = $css_class;
    }
}
