<?php
declare(strict_types=1);

if (!defined('ABSPATH')) {
    exit;
}

if (!function_exists('underscores_child_render_flexible_sections')) {
    function underscores_child_render_flexible_sections(string $field_name = 'sections', ?int $post_id = null): bool
    {
        $rendered = false;

        if (!function_exists('have_rows')) {
            return false;
        }

        $post_id = $post_id ?: (int) get_the_ID();

        if ($post_id <= 0 || !have_rows($field_name, $post_id)) {
            return false;
        }

        while (have_rows($field_name, $post_id)) {
            the_row();

            $layout = (string) get_row_layout();

            if ($layout === '') {
                continue;
            }

            $template_slug = 'partials/sections/' . str_replace('_', '-', $layout);

            if (!locate_template($template_slug . '.php', false, false)) {
                continue;
            }

            get_template_part(
                $template_slug,
                null,
                [
                    'layout' => $layout,
                    'post_id' => $post_id,
                ]
            );

            $rendered = true;
        }

        return $rendered;
    }
}

if (!function_exists('underscores_child_add_heading_ids')) {
    /**
     * Add id attributes to <h2> headings in single post content.
     * IDs match the TOC generated by partials/components/post-toc.php.
     *
     * @param string $content
     * @return string
     */
    function underscores_child_add_heading_ids($content)
    {
        if (!is_singular('post')) {
            return $content;
        }

        return preg_replace_callback(
            '#<h2([^>]*)>(.*?)</h2>#is',
            static function ($m) {
                $attrs = $m[1];
                $html = $m[2];
                // Skip if already has id
                if (preg_match('/\bid\s*=/i', $attrs)) {
                    return $m[0];
                }
                $text = trim(wp_strip_all_tags($html));
                $id = sanitize_title($text);
                if ($id === '') {
                    return $m[0];
                }
                return '<h2' . $attrs . ' id="' . esc_attr($id) . '">' . $html . '</h2>';
            },
            $content
        );
    }
}
add_filter('the_content', 'underscores_child_add_heading_ids', 20);

/**
 * Add the design's `.logo` class to the custom-logo link so header styling
 * applies without wrapping it in a second anchor. Hooked only around the
 * the_custom_logo() call in header.php.
 */
function underscores_child_logo_class(string $html): string
{
    return str_replace('class="custom-logo-link"', 'class="custom-logo-link logo"', $html);
}
